Python/ch 04/week 2/code/todo/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('', views.home, name="home"),
    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name="logout"),
    path('register/', views.register, name="register"),
]

Python/ch 04/week 2/code/todo/users/models.py
from django.db import models

# Create your models here.

Python/ch 04/week 2/code/todo/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
# '/users/' => 홈페이지
# '/users/login' => 로그인 화면


def home(request):
    return render(request, 'users/home.html')


def login_user(request):
    # /users/login GET  -> 로그인 창을 render
    # /users/login POST  -> 로그인(유저 검증)
        # 만약에 username, password 넘어온 값이 DB에 저장된 값과 같다면,
        #     로그인
        # 아니면,
        #     실패
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            # 1. 사용자가 로그인 되었을 때
            messages.success(request, "로그인 성공")
            return redirect('todos:home')
        else:
            # 2. 로그인이 되지 않았을 때
            messages.warning(request, '로그인 실패, 다시 시도해 주세요.')
            return redirect('users:login')

    else:
        return render(request, 'users/login.html')


def logout_user(request):
    # 유저를 로그아웃 시킨다.
    logout(request)
    # 유저에게 로그아웃이 되었다는 메세지를 전달한다.
    messages.success(request, "로그아웃 되었습니다.")
    return redirect('todos:home')

# 회원가입 시키기
def register(request):
    if request.method == "POST":
        # db에 사용자 정보 저장
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('users:login')
    else:
        # 회원 정보를 받는 form.html 보여주기
        form = UserCreationForm()
        return render(request, 'users/register.html', {"form":form})

Python/ch 04/week 2/code/todo/users/templates/users/base.html
<!doctype html>
<html lang="ko">
    <head>
        <title>TODO APP</title>
        <!-- meta tags 필요 -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <body>
        <!-- Optional JavaScript -->
        <!-- 먼저 jQuery가 오고 그 다음 Popper.js 그 다음 Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="{% url 'users:home' %}">TODO APP</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:login' %}">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'shouts:home' %}">고객센터</a>
                    </li>
                </ul>
            </div>
        </nav>
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% endfor %}
        {% endif %}

        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

Python/ch 04/week 2/code/todo/users/templates/users/home.html
{% extends 'users/base.html' %}

{% block content %}
    <h1 class="text-center">Welcome to TODO APP</h1>
    {% if user.is_authenticated %}
        <p>이름 : {{ user.first_name }} {{ user.last_name }}</p>
        <p>이메일 : {{ user.email }}</p>
        <p>아이디 : {{ user }}</p>
        <p>비밀번호 : {{ user.password }}</p>
    {% endif %}
{% endblock %}

Python/ch 04/week 2/code/todo/users/templates/users/login.html
{% extends 'users/base.html' %}

{% block content %}
    <div class="col-md-6 offset-md-3">
        <h1 class="text-center">로그인</h1>
        <form method="POST" action="{% url 'users:login' %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="exampleInputEmail1">Username</label>
                <input type="text" class="form-control" name="username" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter username">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Password</label>
                <input type="password" class="form-control" name="password" id="exampleInputPassword1" placeholder="Password">
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
{% endblock %}

Python/ch 04/week 2/code/todo/users/templates/users/register.html
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
</form>