Python/ch 03/week3 - Django ORM/ch 01 - django ORM/BONBON/BONBON/articles/urls.py
from django.urls import path
from . import views 

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('<int:aid>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:aid>/edit/', views.edit, name='edit'),
    path('<int:aid>/update/', views.update, name='update'),
    path('<int:aid>/delete/', views.delete, name='delete'),
]

Python/ch 03/week3 - Django ORM/ch 01 - django ORM/BONBON/BONBON/bonbon/urls.py
from django.contrib import admin
from django.urls import path, include

from pastlife import views 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('pastlife/', views.pastlife),
    path('articles/', include('articles.urls')),
]

Python/ch 03/week3 - Django ORM/ch 01 - django ORM/BONBON/BONBON/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.TextField()
    content = models.TextField()
    
    def __repr__(self):
        return f"<{self.title} : {self.content}>"
    
    def __str__(self):
        return f"<{self.title} : {self.content}>"

Python/ch 03/week3 - Django ORM/ch 01 - django ORM/BONBON/BONBON/pastlife/models.py
from django.db import models

# Create your models here.
class Job(models.Model):
    name = models.TextField()
    job = models.TextField()
    
    def __repr__(self):
        return f"<{self.name} : {self.job}>"
    
    def __str__(self):
        return f"<{self.name} : {self.job}>"
     

Python/ch 03/week3 - Django ORM/ch 01 - django ORM/BONBON/BONBON/articles/views.py
from django.shortcuts import render, redirect
from .models import Article

# /articles          -> 모든 글을 보여주는 곳
# /articles/1        -> 글 상세하게 보는 곳
# /articles/new      -> 새 글 작성
# /articles/create   -> 새 글 저장
# /articles/1/edit   -> 글 편집
# /articles/1/update -> 글 수정
# /articles/1/delete -> 글 삭제 

def index(request):
    articles = Article.objects.all()
    return render(request, 'articles/index.html', {"articles":articles})
    
def new(request):
    return render(request, 'articles/new.html')
    
def create(request):
    title = request.GET.get('title')
    content = request.GET.get('content')
    
    article = Article(title=title, content=content)
    article.save()

    # return redirect('articles:detail', aid = article.id)
    return redirect('articles:index')
    
def detail(request, aid):
    article = Article.objects.get(id=aid)
    return render(request, 'articles/detail.html', {"article":article})   
    
def edit(request, aid):
    article = Article.objects.get(id=aid)
    return render(request, 'articles/edit.html', {"article":article}) 
    
def update(request, aid):
    article = Article.objects.get(id=aid)
    article.title = request.GET.get('title')
    article.content = request.GET.get('content')
    article.save()
    
    # return redirect('articles:detail', aid = article.id)
    return redirect('articles:index')
    
def delete(request, aid):
    article = Article.objects.get(id=aid)
    article.delete()
    
    # return redirect('/articles')   
    return redirect('articles:index')
    

Python/ch 03/week3 - Django ORM/ch 01 - django ORM/BONBON/BONBON/pastlife/views.py
from django.shortcuts import render
from faker import Faker
# from pastlife.models import Job #현재 같은 레벨에 있음
from .models import Job
import os
import requests
import json

# Create your views here.
def index(request):
    return render(request, 'pastlife/index.html')
    
def pastlife(request):
    # 이름을 받아, faker를 통해 가짜 데이터를 만들어 같이 보냄!
    name = request.GET.get('name')
    
    # 만약 해당 이름이 DB에 저장되어 있다면, 그 직업을 가져옴
    # (DB에서 해당 이름의 레코드가 있는지 찾아본다)!
    # 없으면, faker를 통해 DB에 추가하고, 그 값을 가져옴
    
    person = Job.objects.filter(name=name).first() # 칼럼name = 받은값name 인지 # 아래 코드와 같음!
    # person = Job.objects.get(name=name)
    if person : # None이 아니면,
        job = person.job
    else:
        job = Faker('ko_KR').job()
        new_person = Job(name=name, job=job)
        new_person.save()
     
    # gif
    GIPHY_KEY = os.getenv('GIPHY_KEY')
    
    url = "http://api.giphy.com/v1/gifs/search?api_key={}&q={}&limit=1&lang=ko".format(GIPHY_KEY,job)
    response = requests.get(url).json()
    img_url = response.get("data")[0].get("images").get("original").get("url")
    
    context =  {"name":name, "job":job, "img_url":img_url}
    
    return render(request, 'pastlife/pastlife.html', context)

Python/ch 03/week3 - Django ORM/ch 01 - django ORM/BONBON/BONBON/articles/templates/articles/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!--부트스트랩-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/css/bootstrap.min.css" integrity="sha384-PDle/QlgIONtM1aqA2Qemk5gPOE7wFq8+Em+G/hmo5Iq0CCmYZLv3fVRDJ4MMwEA" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/js/bootstrap.min.js" integrity="sha384-7aThvCh9TypR7fIc2HV4O/nFMVCBwyIUKL8XCtKE+8xgCgl/PQGuFsvShjr74PBp" crossorigin="anonymous"></script>
    <!-- font awesome-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>First Django!</title>
</head>
<body>
       <nav class="navbar navbar-expand-lg navbar-light bg-light sticky" style="z-index: 1;">
        <a class="navbar-brand" href="#">MySite</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        
         <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item active">
                <a class="nav-link" href="#">Q&A <span class="sr-only">(current)</span></a>
              </li>
            </ul>
        </div>
        
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'articles:index' %}">글목록 <span class="sr-only"></span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/">전생앱 <span class="sr-only"></span></a>
            </li>
            </ul>
        </div>
        </nav>
    {% block body %}
    
    {% endblock %}
    
    
</body>
</html>

Python/ch 03/week3 - Django ORM/ch 01 - django ORM/BONBON/BONBON/articles/templates/articles/detail.html
{% extends 'articles/base.html' %}
{% block body %}

<div class="container" style="text-align:center;">
    <br><br>
    <div class="card">
      <h5 class="card-header">{{article.title}}</h5>
      <div class="card-body">
        <h5 class="card-title">{{article.content}}</h5>
        <a href="{% url 'articles:edit' i.id %}" class="btn btn-dark btn-sm">수정</a>
        <a href="{% url 'articles:delete' i.id %}" class="btn btn-dark btn-sm">삭제</a></td>
        <a class="btn btn-dark btn-sm" href="/articles">목록</a>
      </div>
    </div>
</div>


{% endblock %}

Python/ch 03/week3 - Django ORM/ch 01 - django ORM/BONBON/BONBON/articles/templates/articles/edit.html
{% extends 'articles/base.html' %}


{% block body %}
<div class="container">
    <h1> 게시물 수정</h1>
    <form action="{% url 'articles:update' article.id %}">
      <div class="form-group">
        <label for="exampleFormControlInput1">제목</label>
        <input type="text" class="form-control" id="exampleFormControlInput1" name="title" value="{{article.title}}">
      </div>

      <div class="form-group">
        <label for="exampleFormControlTextarea1">Example textarea</label>
        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="content">{{article.content}}</textarea>
      </div>
      <button type="button" class="btn btn-warning" onClick="location.href='/articles'">취소</button>
      <input type="submit" class="btn btn-warning" value="수정"/>
    </form>
</div>
{% endblock %}

Python/ch 03/week3 - Django ORM/ch 01 - django ORM/BONBON/BONBON/articles/templates/articles/index.html
{% extends 'articles/base.html' %}
{% block body %}

<div class="container" style="text-align:center;">
    <hr>
    <h1>게시판</h1>
    <br>
    <a href="{% url 'articles:new' %}" style="text-align:center;" class="btn btn-success">새 글 쓰기</a>
    <hr>
</div>
<div class="container">
    <h2>글 목록</h2>
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">no</th>
          <th scope="col">title</th>
          <th scope="col">content</th>
        </tr>
      </thead>
      <tbody>
        {% for i in articles %}
        <tr>
          <th scope="row">{{i.id}}</th>
          <td>
            <a href="{% url 'articles:detail' i.id %}">{{i.title}}</a>
          </td>
          <td>{{i.content}}     
              <a href="{% url 'articles:edit' i.id %}" class="btn btn-dark btn-sm">수정</a>
              <a href="{% url 'articles:delete' i.id %}" class="btn btn-dark btn-sm">삭제</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
</div>


{% endblock %}

Python/ch 03/week3 - Django ORM/ch 01 - django ORM/BONBON/BONBON/articles/templates/articles/new.html
{% extends 'articles/base.html' %}

{% block body %}
<div class="container">
    <h1> 새 글 등록</h1>
    
    <form action="{% url 'articles:create' %}">
      <div class="form-group">
        <label for="exampleFormControlInput1">제목</label>
        <input type="text" class="form-control" id="exampleFormControlInput1" value="{{article.title}}" name="title">
      </div>

      <div class="form-group">
        <label for="exampleFormControlTextarea1">내용</label>
        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="content"></textarea>
      </div>
      
      <button type="button" class="btn btn-warning" onClick="location.href='/articles'">취소</button>
      <input type="submit" class="btn btn-warning" value="글쓰기"/>
    </form>
</div>
{% endblock %}

Python/ch 03/week3 - Django ORM/ch 01 - django ORM/BONBON/BONBON/pastlife/templates/pastlife/index.html
{% extends 'articles/base.html' %}
{% block body %}
<div class="container">
    <h1>전생앱~</h1>
    <p>전생을 알려드립니다.</p>
      <form action="/pastlife">
        <label for="exampleFormControlInput1">이름 : </label>
        <input type="text" name="name"/>
        <input type="submit" class="btn btn-warning" value="찾기"/>
    </form>
</div>


{%endblock%}

Python/ch 03/week3 - Django ORM/ch 01 - django ORM/BONBON/BONBON/pastlife/templates/pastlife/pastlife.html
{% extends 'articles/base.html' %}
{% block body %}
<div class="container">
    <h1>{{name}}님의 전생은 {{job}}였습니다.</h1>
    <img src="{{img_url}}"></img>
</div>
{%endblock%}