Python/ch 04/week 1/django-first_local/board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('', views.article_list, name='article_list'),                             # 글목록
    # path('new/', views.new_article, name='new_article'),                         # new.html
    path('create/', views.create_article, name='create_article'),                  # 글쓰기

    path('<int:article_id>/', views.article_detail, name='article_detail'),        # detail.html
    # path('<int:article_id>/edit', views.edit_article, name='edit_article'),        # edit.html
    path('<int:article_id>/update/', views.update_article, name='update_article'),  # update
    path('<int:article_id>/delete/', views.delete_article, name='delete_article'),  # delete

    # 댓글
    path('<int:article_id>/create_comment/', views.create_comment, name='create_comment'),
    path('<int:article_id>/delete_comment/<int:comment_id>',
         views.delete_comment,
         name='delete_comment'),
]

Python/ch 04/week 1/django-first_local/first_local/urls.py
from django.contrib import admin
from django.urls import path, include

# upload setting
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
    path('sns/', include('sns.urls')),
]

# Dev Only (개발 서버에서 media/ 파일들을 서빙 미지원) 그래서 아래의 코드를 써서 직접 확인해야함
# setiings의 DEBUG=False가 되면, 자동으로 밑의 함수가 빈 코드로 return됨
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Python/ch 04/week 1/django-first_local/sns/urls.py
from django.urls import path
from . import views

app_name='sns'

urlpatterns = [
    path('', views.posting_list, name='posting_list'),
    path('<int:posting_id>/', views.posting_detail, name='posting_detail'),
    path('create/', views.create_posting, name='create_posting'),

    path('<int:posting_id>/comment/create/', views.create_comment, name='create_comment'),
]

Python/ch 04/week 1/django-first_local/board/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.TextField(default='')
    content = models.TextField(default='')
    like = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.id}: {self.title[:20]}'

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    content = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.article.title}:{self.content}'

Python/ch 04/week 1/django-first_local/sns/models.py
from django.db import models
# ImageKit
from imagekit.models import ImageSpecField, ProcessedImageField
from imagekit.processors import ResizeToFit

class Posting(models.Model):
    content = models.TextField(default='')
    icon = models.CharField(max_length=20, default='fas fa-question')

    # 원본 유지 저장
    # upload URL => /media/posting/origin/그날날짜
    # image = models.ImageField(blank=True, upload_to='posting/origin/%Y%m%d')

    # resize된 이미지 저장
    image = ProcessedImageField(
        upload_to='posting/resize/%Y%m%d',
        processors=[ResizeToFit(width=960, upscale=False)], # 크면 960으로줄이는데, 작은게 들어오면 늘리진 X
        format='JPEG',
    )

    # thumbnail
    image_thumbnail = ImageSpecField(
        source='image',
        processors=[ResizeToFit(width=320, upscale=False)],
        format='JPEG',
        options={'quality':60},  # 원본 퀄리티의 60%
    )


    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.id} : {self.content[:20]}'

    def save(self,*args, **kwargs):
        super().save(*args, **kwargs)
        print()
        print(f'==== Save Posting with id : {self.id} ===')
        print(f'     content: {self.content}')
        if self.image:
            print(f'     image_size: {self.image.width}px * {self.image.height}px : {round(self.image.size / 1024)}kb')
        print('============================================')

class Comment(models.Model):
    posting = models.ForeignKey(Posting, on_delete=models.CASCADE)
    content = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.posting.content[:10]} : {self.content[:20]}'

Python/ch 04/week 1/django-first_local/board/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Article,Comment
from IPython import embed

# Create your views here.
def article_list(request):
    articles = Article.objects.all()
    return render(request, 'board/list.html', {
        'articles':articles,
    })

def article_detail(request, article_id):
    # 값이 없을 때 404 error!
    article = get_object_or_404(Article, id=article_id)
    comments = article.comment_set.all()
    return render(request, 'board/detail.html', {
        'article':article,
        'comments':comments,
    })

# def new_article(request):
#     return render(request, 'board/new.html')

def create_article(request):
    if request.method=='GET':
        return render(request,'board/new.html')
    elif request.method=='POST':
        article = Article()
        article.title = request.POST.get('title')
        article.content = request.POST.get('content')
        article.save()
        return redirect('board:article_detail', article.id)

def update_article(request, article_id):
    article = get_object_or_404(Article, id=article_id)

    if request.method=='GET':
        return render(request,'board/edit.html', {
            'article':article,
        })
    else:
        article.title = request.POST.get('title')
        article.content = request.POST.get('content')
        article.save()
        return redirect('board:article_detail', article.id)

def delete_article(request, article_id):
    if request.method == 'POST':
        article = get_object_or_404(Article, id=article_id)
        article.delete()
    return redirect('board:article_list')

# 댓글부분!
def create_comment(request, article_id):
    if request.method == 'POST':
        comment = Comment()
        # 이 댓글의 글은 이 글이야
        comment.article = get_object_or_404(Article, id=article_id)
        comment.content = request.POST.get('comment')
        comment.save()
    return redirect('board:article_detail', article_id)

def delete_comment(request, article_id, comment_id):
    # article = get_object_or_404(Article, article_id)
    if request.method == 'POST':
        comment = get_object_or_404(Comment, id=comment_id)
        comment.delete()
    return redirect('board:article_detail', article_id)

Python/ch 04/week 1/django-first_local/sns/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Posting,Comment

def posting_list(request):
    # postings = Posting.objects.all().order_by('updated_at')  # 마지막 수정이 맨뒤
    postings = Posting.objects.all().order_by('-updated_at') # 마지막 수정이 맨위,
    return render(request, 'sns/list.html', {
        'postings':postings,
    })

def posting_detail(request, posting_id):
    posting = get_object_or_404(Posting, id=posting_id)
    comments = posting.comment_set.all().order_by('-created_at')
    return render(request, 'sns/detail.html', {
        'posting':posting,
        'comments':comments,
    })

def create_posting(request):
    if request.method == 'POST':
        posting = Posting.objects.create(
            content=request.POST.get('content'),
            icon = request.POST.get('icon'),
            image=request.FILES.get('image'),
        )
        return redirect('sns:posting_detail', posting.id)
    else:
        return redirect('sns:posting_list')

def create_comment(request, posting_id):
    posting = get_object_or_404(Posting, id=posting_id)
    if request.method=='POST':
        comment = Comment()
        comment.content = request.POST.get('comment')
        comment.posting = posting
        comment.save()
    return redirect('sns:posting_detail', posting.id)

Python/ch 04/week 1/django-first_local/board/templates/board/_comment.html
    <form action="{% url 'board:create_comment' article.id %}" method ="POST">
        {% csrf_token %}
        <label for="comment">댓글</label>
        <input type="text" name="comment" id="comment" autofocus>
    </form>

    {% if comments %}
        <ul>
        {% for comment in comments %}
            <li>{{ comment.content }}</li>
            <form action="{% url 'board:delete_comment' article.id comment.id %}" method="post">
                {% csrf_token %}
                <button type="submit">삭제</button>
                {# TODO : 이거 만들어라#}
            </form>
        {% endfor %}
        </ul>

    {% endif %}

Python/ch 04/week 1/django-first_local/board/templates/board/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

Python/ch 04/week 1/django-first_local/board/templates/board/detail.html
{% extends 'board/base.html' %}

{% block body %}
    <h1>{{article.title}}</h1>
    <p>{{ article.content }}</p>
    <p>{{ article.like }}</p>

    <a href="{% url 'board:article_list' %}"><button>목록으로</button></a>
    <a href="{% url 'board:update_article' article.id %}"><button>수정</button></a>

    <form action="{% url 'board:delete_article' article.id %}" method="post">
        {% csrf_token %}
        <button type="submit">삭제</button>

    </form>
    {% include 'board/_comment.html' %}
{% endblock %}

Python/ch 04/week 1/django-first_local/board/templates/board/edit.html
{% extends 'board/base.html' %}

{% block body %}
    <h1>New Articles</h1>
{#    <form action="{% url 'board:create_article' %}" method="post">#}
    <form method="post">     {# 내 자리로 점프! #}
        {% csrf_token %}
        <div>
            <label for="title">Title</label>
            <input type="text" name="title" id="title" value="{{ article.title }}">
        </div>
        <div>
            <label for="content">Content</label>
            <textarea name="content" id="content" cols="30" rows="10">{{article.content}}</textarea>
        </div>
        <div>
            <input type="submit">
        </div>
    </form>
{% endblock %}

Python/ch 04/week 1/django-first_local/board/templates/board/list.html
{%  extends 'board/base.html' %}

{% block body %}
    <a href="{% url 'board:create_article' %}"><button>새글쓰기</button></a>
    {% if articles %}
        <ul>
            {% for article in articles %}
                <li>
                    <a href="{% url 'board:article_detail' article.id %}">
                        {{ article.title }} - ({{ article.comment_set.count }})
                    </a>
                </li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}

Python/ch 04/week 1/django-first_local/board/templates/board/new.html
{% extends 'board/base.html' %}

{% block body %}
    <h1>New Articles</h1>
{#    <form action="{% url 'board:create_article' %}" method="post">#}
    <form method="post">     {# 내 자리로 점프! #}
        {% csrf_token %}
        <div>
            <label for="title">Title</label>
            <input type="text" name="title" id="title">
        </div>
        <div>
            <label for="content">Content</label>
            <textarea name="content" id="content" cols="30" rows="10"></textarea>
        </div>
        <div>
            <input type="submit">
        </div>
    </form>
{% endblock %}